### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by connorryanbaker** [kkossally/Hoppd#1]
#### MVP List

- We talked briefly about there being flexibility to this order, particularly around the `Search` feature. To me, the
  most reasonable spot to stick this feature would be after Drinks CRUD, but we can talk more about this as the project
  is getting built out. Drinks CRUD means hooking our app up to AWS for image upload, the rest of the features are more or less
  straightforward.

#### Schema

- Let's talk about including an `imageURL` for Users. It makes sense that on account creation users should have some kind of default
  image like on unTappd and then be able to upload a separate profile photo later, but let's walk through implementing this in our
  meeting Tuesday.
- I would argue that the image associated with a Beer should be pulled from S3 and that the inclusion of an imageURL for Beer may
  not be necessary.
- Let's also talk about your goals for `Locations`, namely if you are planning on using GoogleMaps. I would encourage this as it can
  only add to the project and make it feel more full featured, but let's discuss.
- Checkins table looks good - `body` refers to the optional review and `rating` is a floating point with an appropriate range.

#### Backend Routes

- My main consideration is for your Users routes - a GET request to `/api/user` intended to return the user's profile information will
  likely be easier to implement as a request for a user with a route wildcard for the user's id, like GET `api/users/:id`.

#### Frontend Routes

- All in all very reasonable and well broken down, index, index-item, form etc. Untappd has a navbar that displays for every page as well
  as a side bar on the right hand side that displays different page specific information. This sidebar component will need to render different
  components at different routes. Let's talk through how we might approach this on Tuesday.

#### Sample State

- The only thing that comes to mind is how we will treat locations and what their role is throughout the app. Otherwise this looks great, no
  duplication of objects, references through ids, all excellent.

Keep up the good work! Looking forward to talking more at length on Tuesday.

**Comment by kkossally** [comment]
Thanks Connor,

This is extremely helpful!

Best,

Kafele Kossally
